#  Archivo de mensajes del juego Piedra, Papel y Tijera(main.py)


SP_MESSENGES = { "msg" : 'Elije una opción: \n[R]Piedra, \n[P]apel, \n[S]Tijeras, \n[L]agarto, \nSpoc[K], \n[Q]uit: ',
    "electionR" : '\nEl ordenador elije Piedra',
    "electionP" : '\nEl ordenador elije Papel',
    "electionS" : '\nEl ordenador elije Tijeras',
    "electionL" : '\nEl ordenador elije Lagarto',
    "electionK" : '\nEl ordenador elije Spock',
    "win" : '\n¡¡¡HAS GANADO!!!',
    "lose" : '\n¡¡¡HAS PERDIDO!!!',
    "draw" : '\nHA SIDO UN EMPATE',
    "games" : '\nPor favor, introduce el número de veces que quieres que juegue: ',
    "error1" : 'Has cambiado el archivo del juego. Por favor, restaura sus valores o borralo',
    "waiting" : 'El ordenador está jugando, por favor espera...',
    "continue" : 'Pulsa [S] para volver a jugar. Otra tecla para salir.',
    "newplayer" : 'Por favor, introduce tu nombre para jugar: ',
    "typegame" : 'Por favor, pulsa [1] para jugar o [2] para modo automático: ',
    "welcome" : 'Bienvenido ',
    "error2" : 'No has introducido un número valido',
    "results_a" : '\nLlevas ',
    "victorys" : ' Victorias',
    "defeats" : ' Derrotas',
    "draws" : ' Empates',
    "lenguage" : '[1] Español \n[2] English \n',
    "totalimputs" : "El total de imputs es: ",
    "totalgoods" : "El total de imputs buenos es: ",
    "totalbads" : "El total de imputs malos es: ",
    "sesionimputs" : "Imputs en la partida: ",
    "sesiongoods" : "Imputs buenos en la partida: ",
    "sesionbads" : "Imputs malos en la partida: ",
    "totaltime" : "Tiempo total de ejecucion del programa: ",
    "sesiontime" : "Tiempo de esta partida: "
    }
